services:
  - type: web
    name: petstore-backend
    runtime: java
    plan: starter
    branch: main
    rootDir: backend
    buildCommand: ./mvnw -B package -DskipTests
    startCommand: java -Dserver.port=$PORT -jar target/petstore-backend-0.0.1-SNAPSHOT.jar
    autoDeploy: true
    envVars:
      - key: JAVA_VERSION
        value: 17

  - type: static
    name: petstore-frontend
    runtime: static
    plan: starter
    branch: main
    rootDir: frontend
    buildCommand: npm install && npm run build
    publishPath: dist
    autoDeploy: true
    envVars:
      - key: NODE_ENV
        value: production
